// Code generated by command: go run gen.go -out internal/ivfsearch/ivfsearch_amd64.s. DO NOT EDIT.

#include "textflag.h"

// func computeCentroidDistsAVX2(qGrid *[14]float32, ct *float32, dists *float32)
// Requires: AVX, FMA3
TEXT ·computeCentroidDistsAVX2(SB), NOSPLIT, $0-24
	MOVQ         qGrid+0(FP), AX
	MOVQ         ct+8(FP), CX
	MOVQ         dists+16(FP), DX
	VBROADCASTSS (AX), Y0
	XORQ         BX, BX

loop_dim0:
	CMPQ    BX, $0x00004000
	JAE     done_dim0
	VMOVUPS (CX)(BX*1), Y1
	VMOVUPS 32(CX)(BX*1), Y2
	VSUBPS  Y0, Y1, Y1
	VSUBPS  Y0, Y2, Y2
	VMULPS  Y1, Y1, Y1
	VMULPS  Y2, Y2, Y2
	VMOVUPS Y1, (DX)(BX*1)
	VMOVUPS Y2, 32(DX)(BX*1)
	ADDQ    $0x00000040, BX
	JMP     loop_dim0

done_dim0:
	MOVQ $0x00000001, SI

loop_dim:
	CMPQ         SI, $0x0000000e
	JAE          done_dim
	MOVQ         SI, BX
	MOVQ         SI, BX
	SHLQ         $0x02, BX
	ADDQ         AX, BX
	VBROADCASTSS (BX), Y0
	XORQ         BX, BX
	MOVQ         SI, DI
	SHLQ         $0x0e, DI
	ADDQ         CX, DI

loop_dim_inner:
	CMPQ        BX, $0x00004000
	JAE         done_dim_inner
	VMOVUPS     (DI)(BX*1), Y1
	VMOVUPS     32(DI)(BX*1), Y2
	VSUBPS      Y0, Y1, Y1
	VSUBPS      Y0, Y2, Y2
	VMOVUPS     (DX)(BX*1), Y3
	VMOVUPS     32(DX)(BX*1), Y4
	VFMADD231PS Y1, Y1, Y3
	VFMADD231PS Y2, Y2, Y4
	VMOVUPS     Y3, (DX)(BX*1)
	VMOVUPS     Y4, 32(DX)(BX*1)
	ADDQ        $0x00000040, BX
	JMP         loop_dim_inner

done_dim_inner:
	ADDQ $0x00000001, SI
	JMP  loop_dim

done_dim:
	VZEROUPPER
	RET

// func computeBlocksAVX2(blocks *int16, nblocks int, qScaled *[16]float32, dists *float32)
// Requires: AVX, AVX2, FMA3
TEXT ·computeBlocksAVX2(SB), NOSPLIT, $0-32
	MOVQ         blocks+0(FP), AX
	MOVQ         nblocks+8(FP), CX
	MOVQ         qScaled+16(FP), DX
	MOVQ         dists+24(FP), BX
	VBROADCASTSS 56(DX), Y0
	XORQ         SI, SI
	XORQ         DI, DI

loop_blocks:
	CMPQ         SI, CX
	JAE          done_blocks
	VXORPS       Y1, Y1, Y1
	VBROADCASTSS (DX), Y2
	VMOVUPS      (AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 4(DX), Y2
	VMOVUPS      16(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 8(DX), Y2
	VMOVUPS      32(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 12(DX), Y2
	VMOVUPS      48(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 16(DX), Y2
	VMOVUPS      64(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 20(DX), Y2
	VMOVUPS      80(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 24(DX), Y2
	VMOVUPS      96(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 28(DX), Y2
	VMOVUPS      112(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 32(DX), Y2
	VMOVUPS      128(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 36(DX), Y2
	VMOVUPS      144(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 40(DX), Y2
	VMOVUPS      160(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 44(DX), Y2
	VMOVUPS      176(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 48(DX), Y2
	VMOVUPS      192(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VBROADCASTSS 52(DX), Y2
	VMOVUPS      208(AX)(DI*1), X3
	VPMOVSXWD    X3, Y3
	VCVTDQ2PS    Y3, Y3
	VMULPS       Y0, Y3, Y3
	VSUBPS       Y2, Y3, Y3
	VFMADD231PS  Y3, Y3, Y1
	VMOVUPS      Y1, (BX)
	ADDQ         $0x00000020, BX
	ADDQ         $0x000000e0, DI
	ADDQ         $0x00000001, SI
	JMP          loop_blocks

done_blocks:
	VZEROUPPER
	RET
